### PR TITLE
Modifying assigning of groups on registeration

### PR DESCRIPTION
**Pull request by prahasR**

### CODE REVIEW

**Comment by prahasR** [comment]
for solving #1, please review @kartik-pant-23. Please look at both the commits.

**Review by kartik-pant-23 — COMMENTED** [review]
Aren't you updating `noOfMembers` by 2? First in line number 13, then in line 22 as well you are adding 1. I suggest you look into `inc` in mongoose, which increment value of the field by provided value.

**Comment by kartik-pant-23** [comment]
Please make only one commit per pull request. Please do one more PR with single commit fixing all issues, that would be great help.

**Comment by prahasR** [comment]
@kartik-pant-23 please see comments on the issue page.

**Comment by prahasR** [comment]
@kartik-pant-23 I figured out that line 22 can be modified as `Group.findOneandUpdate({<field>:<filter>},{ $inc{<field>:<value>});`. I think this would solve all the issues, please suggest if anything else is to be changed?

**Comment by kartik-pant-23** [comment]
Look at this [comment](https://github.com/kartik-pant-23/IIITB-Hogwarts_Hacktoberfest/issues/1#issuecomment-933376203), I have mentioned everything. Also, it would be great if you can make one more PR with all issues fixed and a single commit.

**Comment by prahasR** [comment]
@kartik-pant-23 please review. (solves #1 )

**Comment by kartik-pant-23** [comment]
Okay @prahasR, it seems good. From the next time, just try to make a single commit. Kudos!! for your great work.

**Review by kartik-pant-23 — COMMENTED** [review]
Everything looked fine!

**Pull request merged**
