### PR TITLE
added auth middleware

### PR DESCRIPTION
**Pull request by shikhar13012001**
I have made the auth middleware, Please review my PR and let me know if you need any changes, thank you

### CODE REVIEW

**Comment by shikhar13012001** [comment]
> The code looks fine, great work!! Have you also checked this locally? Please confirm, I will accept the PR.

Yes sir, I tested it locally I got two scenarios.

- If the client sent the ```wrong token``` then error is thrown when we read some property of ```undefined user```  
 (I had used JSON response as ``` req.user._id ``` )
    ``` 
    "status": 500,
    "message": "Cannot read property '_id' of null" 
     ```
 
      
- If the client has no ```token```
   we get 
  ``` 
   "status": 500,
    "message": "User must be logged in"
  ```

**Comment by kartik-pant-23** [comment]
Hey @shikhar13012001! for both of the cases can you send status code `401` and the message `Authentication failed!`, that would be easier to handle on the frontend.

**Comment by shikhar13012001** [comment]
@kartik-pant-23 , sir I have made the requested changes , please review my PR and tell me if you need any changes.

**Comment by kartik-pant-23** [comment]
looks fine @shikhar13012001. Great work!! I am accepting the PR. Thank you!!

**Pull request merged**
